### ISSUE TITLE
Related paper

### ISSUE THREAD

**Issue by chengwei0427** [SLAMWang/MGN-GICP#1]
Hi, dear author @SLAMWang 

Thanks for your nice open source work. For some reasons, I cannot download the related papers, can you upload the papers?

```
1. Feature- and Distribution-Based LiDAR SLAM With Generalized Feature Representation and Heuristic Nonlinear Optimization
2. 3D LiDAR Localization based on Novel Nonlinear Optimization Method for Autonomous Ground Robot
```
Or send the preprint papers to my email <960732491@qq.com>

**Comment by Gatsby23** [comment]
> Hi, dear author @SLAMWang
> 
> Thanks for your nice open source work. For some reasons, I cannot download the related papers, can you upload the papers?
> 
> ```
> 1. Feature- and Distribution-Based LiDAR SLAM With Generalized Feature Representation and Heuristic Nonlinear Optimization
> 2. 3D LiDAR Localization based on Novel Nonlinear Optimization Method for Autonomous Ground Robot
> ```
> 
> Or send the preprint papers to my email [960732491@qq.com](mailto:960732491@qq.com)

Same problem, could you sent it to the 546197604@qq.com

**Comment by SLAMWang** [comment]
链接：https://pan.baidu.com/s/1yKSb_GBEesQM3QCGOIiC6A?pwd=jxm0 
提取码：jxm0 
--来自百度网盘超级会员V4的分享

**Comment by chengwei0427** [comment]
Thank you very much!
Problem solved, and I'll close this issue.

**Comment by Gatsby23** [comment]
> 链接：https://pan.baidu.com/s/1yKSb_GBEesQM3QCGOIiC6A?pwd=jxm0 提取码：jxm0 --来自百度网盘超级会员V4的分享

Thank you very much.
